name: SonarQube Code Scan (Test)

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: squ_3ed0149953b131afc3298f18265d027f1616404b
          SONAR_HOST_URL: http://81.69.8.26:9000/